defaults:
  - logging/console_log
  - _self_

# List of paths to audio files of the audiobook.
# If there is more than one file, list order should follow the chronological order of the audio files' contents.
audio_files: ???

# For each audio chunk transcribed, append space to it.
# If this is set, during alignment the transcription will have two spaces between each word,
# so the aligner will always pick a word-level match.
# This maybe slower and is considered a hacky solution, so in most cases it should not be set.
append_space_to_words: false

compute_type: "float16"
batch_size: 16
transcription_model: "large-v2"

# e.g., out/results/yourbookname
result_dir: ???
